"""cambio X

Revision ID: 59c25dd0056c
Revises: 672e6b9f878b
Create Date: 2025-09-13 02:22:28.815593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59c25dd0056c'
down_revision: Union[str, Sequence[str], None] = '672e6b9f878b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personas', 'creado_en',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('personas', 'actualizado_en',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('usuarios', 'creado_en',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_constraint('usuarios_ibfk_1', 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'personas', ['persona_id'], ['id'], ondelete='CASCADE')
    op.drop_column('usuarios', 'is_active')
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('usuarios', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key('usuarios_ibfk_1', 'usuarios', 'personas', ['persona_id'], ['id'])
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=True)
    op.alter_column('usuarios', 'creado_en',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('personas', 'actualizado_en',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('personas', 'creado_en',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_table('estudiantes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('persona_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('matricula', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name='estudiantes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_estudiantes_matricula', 'estudiantes', ['matricula'], unique=True)
    op.create_table('notas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('estudiante_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('evaluacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nota', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], name='notas_ibfk_1'),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], name='notas_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('evaluaciones',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('materia', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('ponderacion', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
