"""add estudiantes

Revision ID: 5e7f78408ee5
Revises: 59c25dd0056c
Create Date: 2025-09-13 02:33:59.047559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e7f78408ee5'
down_revision: Union[str, Sequence[str], None] = '59c25dd0056c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiantes', sa.Column('codigo_est', sa.String(length=30), nullable=True))
    op.drop_index('ix_estudiantes_matricula', table_name='estudiantes')
    op.create_unique_constraint(None, 'estudiantes', ['persona_id'])
    op.create_unique_constraint(None, 'estudiantes', ['codigo_est'])
    op.drop_constraint('estudiantes_ibfk_1', 'estudiantes', type_='foreignkey')
    op.create_foreign_key(None, 'estudiantes', 'personas', ['persona_id'], ['id'], ondelete='CASCADE')
    op.drop_column('estudiantes', 'matricula')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiantes', sa.Column('matricula', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'estudiantes', type_='foreignkey')
    op.create_foreign_key('estudiantes_ibfk_1', 'estudiantes', 'personas', ['persona_id'], ['id'])
    op.drop_constraint(None, 'estudiantes', type_='unique')
    op.drop_constraint(None, 'estudiantes', type_='unique')
    op.create_index('ix_estudiantes_matricula', 'estudiantes', ['matricula'], unique=True)
    op.drop_column('estudiantes', 'codigo_est')
    op.create_table('notas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('estudiante_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('evaluacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nota', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], name='notas_ibfk_1'),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], name='notas_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('evaluaciones',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('materia', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('ponderacion', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
