"""sync evaluaciones/notas models

Revision ID: afeed30f824e
Revises: 5e7f78408ee5
Create Date: 2025-09-13 02:50:16.200342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'afeed30f824e'
down_revision: Union[str, Sequence[str], None] = '5e7f78408ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluaciones', sa.Column('asignacion_id', sa.Integer(), nullable=False))
    op.add_column('evaluaciones', sa.Column('titulo', sa.String(length=120), nullable=False))
    op.add_column('evaluaciones', sa.Column('tipo', sa.Enum('EXAMEN', 'TAREA', 'PROYECTO', 'PRACTICA', 'OTRO', name='tipoevalenum'), nullable=False))
    op.alter_column('evaluaciones', 'ponderacion',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=5, scale=2),
               existing_nullable=False)
    op.create_unique_constraint('uq_eval_asig_titulo', 'evaluaciones', ['asignacion_id', 'titulo'])
    op.create_foreign_key(None, 'evaluaciones', 'asignacion_docente', ['asignacion_id'], ['id'])
    op.drop_column('evaluaciones', 'nombre')
    op.drop_column('evaluaciones', 'descripcion')
    op.drop_column('evaluaciones', 'materia')
    op.add_column('notas', sa.Column('calificacion', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('notas', sa.Column('observacion', sa.String(length=255), nullable=True))
    op.create_index('idx_nota_est', 'notas', ['estudiante_id'], unique=False)
    op.create_unique_constraint('uq_nota_eval_est', 'notas', ['evaluacion_id', 'estudiante_id'])
    op.drop_column('notas', 'nota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas', sa.Column('nota', mysql.FLOAT(), nullable=False))
    op.drop_constraint('uq_nota_eval_est', 'notas', type_='unique')
    op.drop_index('idx_nota_est', table_name='notas')
    op.drop_column('notas', 'observacion')
    op.drop_column('notas', 'calificacion')
    op.add_column('evaluaciones', sa.Column('materia', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('evaluaciones', sa.Column('descripcion', mysql.TEXT(), nullable=True))
    op.add_column('evaluaciones', sa.Column('nombre', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'evaluaciones', type_='foreignkey')
    op.drop_constraint('uq_eval_asig_titulo', 'evaluaciones', type_='unique')
    op.alter_column('evaluaciones', 'ponderacion',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.drop_column('evaluaciones', 'tipo')
    op.drop_column('evaluaciones', 'titulo')
    op.drop_column('evaluaciones', 'asignacion_id')
    # ### end Alembic commands ###
